### ISSUE TITLE
Configuration File of Lang

### ISSUE THREAD

**Issue by Steellgold** [Zoumi-Dev/FacEssential#2]
If you want to improve the visibility of your plugin in a good way, you should add all the messages in the configuration file, so that people who don't know how to do it can modify the messages in the language file for example

Or create a function to get the message directly from the language file (in the language defined in config.yml)

This will advance the external community to create their own language file and propose it for the plugin as a default "verified" language file

**Comment by Zoumi-Dev** [comment]
> If you want to improve the visibility of your plugin in a good way, you should add all the messages in the configuration file, so that people who don't know how to do it can modify the messages in the language file for example
> 
> Or create a function to get the message directly from the language file (in the language defined in config.yml)
> 
> This will advance the external community to create their own language file and propose it for the plugin as a default "verified" language file

I will do this for the next release
